### ISSUE TITLE
Task: Refactor Milestone form to use the database-stored schema

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1007]
#### Describe the task

Milestones is our most complex form.
Refactoring it will require 
- [x] creating a new form schema with all the fields present
- [x] using `oneOf` to switch between milestone types
- [x] writing a separate handle_commit function to translate the one form into multiple database saves

#### Developer info

- [ ] don't forget to update the tasklist and mutation fragments to fetch the new data
- [ ] existing form_change records need to be migrated with:
    - [ ] a migration function that goes through every existing revision, grabs the milestone reporting requirements and creates a new form_change for each of these - and delete (archive) the form_changes for `reporting_requirement`, `payment` and `milestone` tables.
    - [ ] tests for that migration function
    - [ ] thoughts and more testing

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by LindsayMacfarlane** [comment]
@pbastia, @Sepehr-Sobhani and team - congratulations! This was a huge amount of work and is quite the milestone for completion :)

Tested in dev by creating and editing projects. Observations during testing:
-

**Comment by LindsayMacfarlane** [comment]
My mistake @pbastia and @Sepehr-Sobhani - user error. The amendments are there :)

Looks great!
