### ISSUE TITLE
As a CIF user I want to see Emissions intensity Reporting screen before Quarterly Reports in the task list, so that it aligns with my workflow expectations

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1010]
#### Description:

Since we worked on the auto-generation feature, we realized we needed to change the order of Emissions Intensity Reports to be before Quarterly Reports since the date fields entered in Emission Intensity report can be extracted for the purposes of autogenerating reports between the start and end dates. 

**[Wireframe can be found here](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=4093%3A3050)**

#### Acceptance Criteria:

Given I am a CIF administrator
When I am creating or editing a project
And I am reviewing the task list
Then Emissions Intensity Reports should be before Quarterly Reports

#### Development Checklist:

- [ ] Change the order in components/TaskList/index so that EI Reports are before quarterly 
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1010?planning-poker) with ZenHub @BCerki @gurjmatharu @pbastia @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! Looks great. Tested in dev:
1. Creating a new project.
2. Editing a new project 
Experienced no issues and works as expected. Thanks!
