### ISSUE TITLE
Task: Update the text inconsistencies noticed between the wireframe and implementation

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1029]
#### Describe the task

This ticket is for updating the labelling of fields / texts in the CIF app to reflect the latest design, and goes hand in hand with #1101 which addresses field ordering and grouping inconsistencies between the wireframe and implementation.

#### Acceptance Criteria
(Fully refined by @nanyangpro, reach out if having questions.)

**Task List Sub List Items**
- [x] Update "Project overview" to "Project Overview"
- [x] Update "Project managers" to "Project Managers"
- [x] Update "Project contacts" to "Project Contacts"
- [x] Update "Budgets overview" to "Budgets, Expenses & Payments"
- [x] Update "Quarterly reports" to "Quarterly Reports"
- [x] Update "Annual reports" to "Annual Reports"
- [x] Update "Submit changes" to "Submit Changes"
- [x] Update "Review and submit information" to "Review and Submit Information"

**Project Overview**
- [x] Update "Funding Stream RFP" to "RFP Year"

**Project Managers**
- [x] Update "Submit Managers" button to "Submit Project Managers"
- [ ] Update "Email" to "Email:"
- [ ] Update "Position" to "Position:"

**Project Contacts**
- [x] Update "Add a secondary contact" to "Add a Secondary Contact"
- [x] Update "Submit Contacts" button to "Submit Project Contacts"

**Budgets, Expenses & Payments**
- [x] Update "Project Funding Agreement" to "Budgets, Expenses & Payments"
- [x] Update "Max Funding Amount" to "Maximum Funding Amount"
- [x] Update "Province Share Percentage" to "Province's Share Percentage"
- [x] Update "Holdback Percentage" to "Performance Milestone Holdback Percentage"
- [x] Update "Anticipated Funding Amount" to "Anticipated/Actual Funding Amount"

**Milestone Reports**
- [x] Update "Add another milestone report" button to "Add Another Milestone Report"
- [x] Remove "Performance" and "TEIMP" from "Milestone Type"
- [x] Update "Received Date (optional)" to "Report Received Date (optional)"
- [x] Update "Date sent to CSNR (optional)" to "Date Invoice Sent to CSNR (optional)"

**Quarterly Reports**
- [x] Update "Add another quarterly report" button to "Add Another Quarterly Report"
- [x] Update "Received Date (optional)" to "Report Received Date (optional)"

**Emissions Intensity Report Form**
- [x] Update "Add TEIMP Agreement" button to "Add Emissions Intensity Report"
- [x] Update "Status of TEIMP Reporting" to "Status of Emissions Intensity Report
- [x] Update "Project TEIMP Reporting" to "Emissions Intensity Report"
- [x] Update "Measurement period start date" to "TEIMP Start Date"
- [x] Update "Measurement period end date" to "TEIMP End Date"
- [x] Add "/" between 2 fields for "Functional Unit"
- [x] Update "Base Line Emission Intensity (BEI)" to "Baseline Emission Intensity (BEI)"
- [x] Update "Post Project Emission Intensity (optional)" to "Post-Project Emission Intensity (PEI) (optional)"
- [x] Update "Total lifetime emissions reductions (optional)" to "Total Project Lifetime Emissions Reductions"
- [x] Update "Payment percentage of performance milestone amount" to "Payment Percentage of Performance Milestone Amount"
- [x] Update "Date sent to CSNR (optional)" to "Date Invoice Sent to CSNR (optional)"
- [x] Update "Submit TEIMP Report" button to "Submit Emissions Intensity Report"

**Annual Reports**
- [x] Update "Add another annual report" button to "Add Another Annual Report"
- [x] Update "Received Date (optional)" to "Report Received Date (optional)"

**Comment by LindsayMacfarlane** [comment]
Hi @suhafa and @nanyangpro - I was refining this ticket based on the Miro board - I've left some comments for the both of you for clarification.

**Comment by nanyangpro** [comment]
Thanks @LindsayMacfarlane - I didn't receive notifications directly from Miro, thus answered your questions I saw in this [board](https://miro.com/app/board/uXjVOr1AdQs=/?share_link_id=499341865112).

**Comment by nanyangpro** [comment]
Note to self, #1029 and #1011 should go hand in hand, and both needs further refinements (more inconsistency between design and implementation has been recognized than what have been documented).

**Comment by BCerki** [comment]
@nanyangpro I've got a few questions on the AC:
- I'm not totally clear on the `Task List Sub List Items` changes in the different modes. Is the capitalization meant to change always? E.g.`Project Managers` (view) vs `Add project managers` vs. `Edit project managers`?
- `Update "Total lifetime emissions reductions (optional)" to "Total Project Lifetime Emissions Reductions"`--is this not meant to be optional anymore?
- Should capitalisation changes be applied on the summary page too? E.g. `Quarterly Reports not added/updated`

**Comment by nanyangpro** [comment]
Thanks for the questions, @BCerki!
- Yes, in terms of capitalization, let's stick to Title Case (friendly reminder: not Upper Case).
- "(Optional)" makes senses from the data architecture perspective, but has been reported confusing from previous user tests. i.e. some fields **aren't ready to be** entered at certain phases, but **eventually should be** entered, however, they are labelled as "optional", which cause confusion for users. I'm hoping to improve this once we have the mapping with "Project Status" in place in the future, thus being loose on labelling "optional" for fields. For this field, as long as the main part is updated, you can leave "(optional)" in as it is.
- Yes, we want consistency.

**Comment by LindsayMacfarlane** [comment]
Thank you @tmastrom ! Looks fantastic.
