### ISSUE TITLE
Categorize these bugs identified by developers during CIF refactor review

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1033]
These bugs were identified during our review of CIF following the refactor. The bugs below were not introduced by the refactor (they currently exist in dev).

Check off the issue if there is already a card in zenhub covering the bug. If not create a card for the bug & check it off. This ticket can be closed when all issues below have been checked off (not done, just each one has a card).

- [x] create operator: validation errors are shown as a regex & should be more friendly to users. #791
- [x] Project contacts: form status doesn't revert to 'Not Started' after the user clears the primary contact, if there are no secondary contacts (related but not quite the same: #801 )
- [x] Project managers: can't clear an existing manager and then add another one in its place https://github.com/bcgov/cas-cif/issues/1040
- [x] Project Contacts: removing a primary contact, then adding a secondary contact, then removing that secondary contact adds the previously removed primary contact back in https://github.com/bcgov/cas-cif/issues/1042
- [x] Budgets: removing a funding agreement (by setting Is this project funded to "No") shows nothing in the diff at the end. https://github.com/bcgov/cas-cif/issues/1043
- [x] Milestones: Summary still shows the validation errors on "Description" and "Due Date" fields (#804 is either the same bug or related)
- [x] Milestones: Task List status doesn't switch to "Attention Required" when navigating away from the form by using a Task List link, when there are validation errors present https://github.com/bcgov/cas-cif/issues/1041
- [x] Milestones: "Remove" button is awkwardly placed near the description field, it's not clear what it applies to https://github.com/bcgov/cas-cif/issues/1038
- [x] Budgets + TEIMP: if you select "no" on the radio button, there's no "submit" option to proceed in the flow, and the status remains "Not Started". The status might make sense, UX can decide on that, but the lack of a submit feels odd. https://github.com/bcgov/cas-cif/issues/1039
- [x] Milestones: "Professional Designation" is optional, but defaults to "Professional Engineer" and there's no way to unset this (no blank option) https://github.com/bcgov/cas-cif/issues/1037
- [x] Project Form: Undoing changes after introducing validation errors doesn't reset the "Attention Required" in the task list https://github.com/bcgov/cas-cif/issues/1058
- [x] Budgets: Adding a new additional funding source to a funding agreement that already has 1 or more additional funding sources triggers no change in the task list (even with validation errors) and does not show up in the diff. https://github.com/bcgov/cas-cif/issues/1036

**Comment by Sepehr-Sobhani** [comment]
Regarding this one: `All Forms: Undoing changes after introducing validation errors doesn't reset the "Attention Required" in the task list` I only faced the issue on the project form and not other forms, Is that correct?! or I'm missing something here!!

**Comment by mikevespi** [comment]
@Sepehr-Sobhani I'm experiencing the same thing, only on Project Form.

**Comment by Sepehr-Sobhani** [comment]
> @Sepehr-Sobhani I'm experiencing the same thing, only on Project Form.

@mikevespi  Gonna create a card for that one.

**Comment by rdromey** [comment]
All issues have cards
