### ISSUE TITLE
As a CIF User, I want to see a customized task list according to the funding stream

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1051]
#### Description:
Display task list items based on the funding stream of a project. See the full list of each stream below:

**EP:**
1. Project Overview
2. Project Details
3. Budgets, Expenses & Payments
4. Milestone Reports
5. Quarterly Reports
6. Emissions Intensity Report
7. Annual Reports
8. Amendments & Other Revisions
9. Attachments

**IA:**
1. Project Overview
2. Project Details
3. Budgets, Expenses & Payments
4. Milestone Reports
5. Project Summary Report
6. Amendments & Other Revisions
7. Attachments

The following was pulled from the main description of the story as a result of a discussion at backlog grooming. Keeping it here for context
- task list items may be hidden/disabled based on the selected project status, see outcome of #518: the "Forms" tab in the [mapping spreadsheet](https://bcgov.sharepoint.com/:x:/t/00608-ScrumTeam/EbxB55A0pk9Kr-eCTocUvIkB6sWffF4ACkh3oQ5_89dTlg?e=dcgbof&isSPOFile=1).
The status related display of forms will be handled in #924

#### Acceptance Criteria:

Given I am a CIF admin,
When I am viewing a project in the EP funding stream,
Then the task list only shows the forms that apply to EP projects. 

Given I am a CIF admin,
When I am viewing a project in the IA funding stream,
Then the task list only shows the forms that apply to IA projects. 

#### Development Checklist:

- [x] Add IA items to our form structure in `useFormStructure` (see `app/data/formPages/formStructure.tsx`) and conditionally return the appropriate items based on the funding stream.
- [ ] If the above implementation begins to feel unclear to read, an alternative would be to have a form structure for EP, and one for IA
~~- [ ] Update `create_project_revision` to handle IA only forms~~
^ This will be handled when the project_summary_report is created. The only thing that needs to change in this funtion is adding that form_change record to the loop. https://github.com/bcgov/cas-cif/issues/1061
- [x] Add tests for the IA flow (e2e, integration, and pgTap)
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

**Comment by matthieu-foucault** [comment]
This is potentially a duplicate of #924

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro - can you please confirm if this is a duplicate of #924 as indicated above. Thanks!

**Comment by nanyangpro** [comment]
Thanks for confirming, @LindsayMacfarlane! They are slightly different.

- This ticket addresses the relationship between **Display of Forms** and **Project Funding Streams** (front-end behaviour oriented), thus it's under the IA epic.
- #924 is trying to reflect all findings summarized in the "Forms" tab in the mapping spreadsheet above, which covers the relationship between **Display of Forms** and **Project Funding Streams** and **Project Status** (back-end logic oriented). I presume #924 will be broken down into smaller pieces when it comes to refinement anyway.

**Comment by mikevespi** [comment]
As decided at todays backlog refinement, I will pull out anything relating to status from this card as they will be handled in #924. This card will only handle displaying forms based on the funding stream.

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1051?planning-poker) with Zenhub @BCerki @gurjmatharu @pbastia @Sepehr-Sobhani @mikevespi @tmastrom @sam-warren

**Comment by dleard** [comment]
@pbastia @mikevespi I think I can remove the attn:developer tag. I was thinking the ordering would be done in the database, which has considerations, but using app/data/formPages/formStructure.tsx makes this simpler.

**Comment by mikevespi** [comment]
@dleard I had put that in, but if we want `create_project_revision` to only create a `form_change` then we may need the list to live in the database too.

**Comment by pbastia** [comment]
I think this `create_project_revision` function doesn't need to depend on the stream, that function is just in charge of duplicating the form_changes for an existing revisions. We'll just need to make sure that all cases of IA and EP are supported.

**Comment by pbastia** [comment]
I think this `create_project_revision` function doesn't need to depend on the stream, that function is just in charge of duplicating the form_changes for an existing revisions. We'll just need to make sure that all cases of IA and EP are supported.

**Comment by BCerki** [comment]
Pie

> I think this `create_project_revision` function doesn't need to depend on the stream, that function is just in charge of duplicating the form_changes for an existing revisions. We'll just need to make sure that all cases of IA and EP are supported.

This is now considered and addressed in the AC

**Comment by LindsayMacfarlane** [comment]
Probably testing to soon...both IA and EP still look to have the same task list.

**Comment by Sepehr-Sobhani** [comment]
> Probably testing to soon...both IA and EP still look to have the same task list.

@LindsayMacfarlane It's now in dev.

**Comment by LindsayMacfarlane** [comment]
Hi @tmastrom - thank you for your work on this. I couldn't select the a funding year for IA, so I wasn't able to check the task list:
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/d1db1f42-5407-4e22-bf43-a29c072a941f)

**Comment by LindsayMacfarlane** [comment]
Nevermind, after refreshing and trying again, it worked. Meets acceptance criteria.
