### ISSUE TITLE
Refine the "Milestone Type" list of options for each Milestone Report

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1054]
#### Description:
On the Milestone Reports page, we can select "Milestone Type" for each milestone report. The current options are: TEIMP, Performance, Advanced, General, Reporting.

**We should discard:**
- TEIMP
- Performance

**And only keep:**
- Advanced
- General
- Reporting

**Note that the Performance Milestone (for EP) and the Project Summary Report Milestone (for IA) have their own pages in terms of reporting, thus we don't need to worry about them:**
- Emissions Intensity Report (for EP)
- Project Summary Report (for IA)

#### Development Checklist:

- [ ] Remove TEIMP from Milestone Type
- [ ] Remove Performance from Milestone Type
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
PO Review (November 8, 2022):
- is this more of a task than a user story?
- medium priority, but would be a good first issue

**Comment by nanyangpro** [comment]
- To me, yes it could be a task. Open for the developers' insights.
- Totally agreed, @LindsayMacfarlane. It's low effort, high value. The current list is wrong and confusing.

**Comment by dleard** [comment]
There are currently only 'Reporting' milestones in Prod (this is important for considering migrations, unless this changes 
we don't need to do any)

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1054?planning-poker) with Zenhub @BCerki @gurjmatharu @mikevespi @Sepehr-Sobhani @dleard

**Comment by mikevespi** [comment]
This seems to have been taken care of in https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/853 , can you confirm that you aren't experiencing the issue anymore @nanyangpro ? If not, I'll move it to closed as a duplicate.

**Comment by nanyangpro** [comment]
Good call, @mikevespi! Tested in DEV/TEST, I confirm that this ticket has been taken care of by #853. Please feel free to close it, thanks!
