### ISSUE TITLE
Research roadmap/research calendar

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1265]
#### Describe the task

Create a research plan after conversing with all stakeholders about how we would like to approach CIF external user application. We need to identify who we can to speak to 

#### Acceptance Criteria
- [x] Build out a rough roadmap for research
- [x] Discuss with LM and JP how we can proceed with this
- [x] Reach out to those who can guide us on this front (Ops? Tech? Program Area experts?)
- [x] Consult with CPR group about public engagement (#1266)
- [x] Update Miro Roadmap 

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by LindsayMacfarlane** [comment]
@suhafa - flagging that this ticket requires refining. We may want to touch base with @jaimiebutton and see where there is alignment with the CPI workshop and the work JK is doing.

**Comment by LindsayMacfarlane** [comment]
Hi @suhafa - thanks for pulling this together! I've started to leave comments on the roadmap, so let's meet and discuss :)

**Comment by suhafa** [comment]
@LindsayMacfarlane Thank you Lindsay! I'll prepare and send invites for it accordingly c:

**Comment by suhafa** [comment]
Met with JK, some next steps:
- Getting some industry operator contacts so that we can test out our testing plan and get some initial feedback.
- Touching base with JK frequently in the upcoming days to get an idea of the workshop and decisions made in general

**Comment by suhafa** [comment]
@LindsayMacfarlane besides reaching out to Shelby for getting some contacts for testing, this ticket is good to be closed. The research roadmap has been created in Miro C:

**Comment by LindsayMacfarlane** [comment]
Thank you for all your work on this @suhafa
