### ISSUE TITLE
As a CIF administrator, I don't want to see the Total Eligible Expenses field on Advance Milestones, so that I am not entering erroneous data in this field

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1513]
#### Description:

The "Total Eligible Expenses" field is not applicable to the Advance Milestone type.
It should be hidden.

Ticket split from #1480

#### Acceptance Criteria:

Given I am a CIF administrator
When I edit a milestone with the Advance Milestone type
Then I don't see the "Total Eligible Expenses" field

#### Development Checklist:

- [x] Investigate if we can make this part of the json schema logic. If this requires too complex of a logic, use some custom code logic in that form instead.

- [x] updating `update_milestone_form_change.sql` to remove `totalEligibleExpenses` if the user decided to change the milestone type from General to any other type.

- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1513?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @mikevespi @sam-warren @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
@pbastia and @sam-warren - please add your estimate.

**Comment by LindsayMacfarlane** [comment]
Hi @sam-warren please add your estimate

**Comment by Sepehr-Sobhani** [comment]
@pbastia Do we need to update the milestone commit handler to make `total_eligible_expenses` `null` if a milestone gets updated from `General` type to `Advanced` type?!

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani. Tested in dev and can confirm that when the 'advanced' milestone type is selected it is no longer displayed.
When advanced is selected:
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/fafb974a-a4ec-4ccf-b6fe-d0b8dca935ca)

When general is selected: 
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/370656ab-d306-4ae4-913b-f528d9f33a3e)
