### ISSUE TITLE
CIF Product Roadmap

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#152]
#### Description:

'Finalize' roadmap for version 1.

#### Checklist:
- [x] create miro board for CIF product roadmap
- [x] start draft
- [x] review with team and update as required
- [x] include" EPICS, goals, value and estimated timeframe
- [x] add in user stories to better show progress and where we are at.

#### Notes:
- roadmap is ever evolving and will need to be updated on a regular basis
