### ISSUE TITLE
As a CIF user, I want to see the differences on Milestone calculated fields since the last revision, so that I can focus on what did change

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1616]
#### Description:

Calculated fields are handled by computed columns, which our current diff logic can't display. For example, diff for calculated gross, net and holdback amounts for a milestone isn't shown on the summary page (page with red/black strikeout). This is likely because the calculated values are not actually part of the schema. 

This card is about implementing diffs in the Milestone form. The calculated values on the Milestone form are:
- Gross Payment Amount This Milestone
- Net Payment Amount This Milestone
- Holdback Amount This Milestone

#### Acceptance Criteria:

Given I have added enough values to complete the calculation for the first time
When I view the summary page
Then the diff displays the newly calculated value

Given I have changed values that affect the calculated value
When I view the summary page
Then the diff displays changed values properly for calculated values

Given I have removed enough values to prevent the calculation
When I view the summary page
Then the diff displays removed calculated values properly

#### Development Checklist:

- [ ] Any front-end calculated values are refactored into computed_columns:
    - N/A for Milestone form
-  [ ] Refactor calculations that calculate values based on info in `project_revision` to calculate based on `form_change` instead (this will also make the calculation dynamic)
    - [ ] project_revision_gross_payment_amount_this_milestone
    - [ ] project_revision_net_payment_amount_this_milestone
    - [ ] project_revision_holdback_amount_this_milestone
- [ ] Query the previously calculated values under `formChangeByPreviousFormChangeId`
- [ ] Pass the previously calculated value to `CustomDiffFields` via `formContext.oldData`
- [ ] Query the latest committed calculated value under `latestCommittedFormChangesFor`
- [ ] Pass the latest committed value to `CustomDiffFields` via `formContext.latestCommittedData`
- [ ] Pass the current calculated value to `CustomDiffFields` via `getSchemaAndDataIncludingCalculatedValues` 
- [ ] update summary form tests
- [ ] update any other mutations or tests as necessary
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)(N/A)
- [ ] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by nanyangpro** [comment]
Backlog refinement Apr 25: This one should be estimated considering that #1231 should already be completed.

**Comment by pbastia** [comment]
@gurjmatharu I can see the diffs on the calculated fields. Thank you for the hard work!
