### ISSUE TITLE
As a CIF administrator, I want to see 'Interim summary report' as a milestone type for IA projects so that I can enter payment information

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1708]
#### Description:

IA project also have an interim summary reports that is associated to a payment, very similarly to EP milestones.
The purpose of this card is to add an "Interim Summary Report" milestone type for IA projects.

#### Acceptance Criteria:

Given I am a CIF administrator
When I enter milestone information for an IA project
Then I can select an "Interim Summary Report" milestone type

Given I am a CIF administrator
When I enter an "Interim Summary Report" milestone
Then I can enter all the same fields as a general milestone, including payment information

And that milestone type has the same information available as a General Milestone.

#### Development Checklist:

- [x] Verify that the payment information is taken into account in our various computed columns that use general milestones 
- [x] Add "Interim Summary Report" to the report_type table
- [x] "Interim Summary Report" milestone type should not be available for EP projects, one option is to filter it out on the front-end
- [x] update `milestone.json` to add the new report type (will need migration to do this because the json is stored in the db)
- [x] update any sql files that include reportType='General': `form_change_calculated_gross_amount_this_milestone`, `form_change_calculated_holdback_amount_this_milestone`, `form_change_calculated_net_amount_this_milestone`, `project_revision_form_changes_for`, `project_revision_latest_committed_form_changes_for`, `update_milestone_form_change`
- [x] update tests

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
@nanyangpro  @Dianadec  flagging this for you

**Comment by nanyangpro** [comment]
Thanks for creating it, @pbastia! - I'll follow up and draft AC as we refine it.

**Comment by pbastia** [comment]
@nanyangpro maybe let's confirm with the business area about what exactly they mean and how we'll solve this, before putting effort into refining the card

**Comment by nanyangpro** [comment]
Thanks @pbastia. For sure, I meant to follow-up with Lindsay/CIF on questions to clarify. :)

**Comment by nanyangpro** [comment]
Additional input from Nicole M. is added to the ticket description. We may need an additional ticket besides #1685 to address auto email reminder for Project Summary Reports (IA).

**Comment by pbastia** [comment]
@nanyangpro thank you! It seems like this is pretty easy - we just need to add a "interim project summary report" milestone type with exactly the same behaviour as a general milestone. Moving to the backlog.

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1708?planning-poker) with Zenhub @BCerki @Sepehr-Sobhani @sam-warren @JoshLarouche @gurjmatharu

**Comment by pbastia** [comment]
I can see the additional milestone report type for IA. Thanks @gurjmatharu !
