### ISSUE TITLE
Review task list design and provide recommendations for design updates

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#358]
#### Describe the task

Review previous design mock-up that was created for a task list and provide UI Design recommendations. 

#### Acceptance Criteria

- [x] Review mock-up
- [x] Get design context from team
- [x] Make design recommendations
- [x] Update mock-up (if required)
- [x] Add updated mock-up to #225 

#### Additional context

- Related to cas-cif #225
- The team had questions around best practices for usability patterns/standards.

**Comment by LindsayMacfarlane** [comment]
FYI @suhafa - as discussed, this ticket is to review the mock-up for a task list previously designed by the team.

**Comment by suhafa** [comment]
Closing this, finished work pertaining to this ticket.
