### ISSUE TITLE
UI Design Roadmap

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#362]
#### Describe the task

Create a design roadmap or refine existing roadmap to better reflect and prioritize required UI design work

#### Acceptance Criteria

- [ ] review existing roadmap
- [ ] determine if we create new roadmap or update existing
- [ ] review with team

#### Additional context

- A UI design roadmap will help us better plan and prioritize upcoming design tasks so that we ensure we are focusing on the right and highest value features.

**Comment by suhafa** [comment]
pulling out this dinosaur – @LindsayMacfarlane is this still relevant for us? I believe we've covered this when we updated the roadmap last time but would love to hear your take on this.
