### ISSUE TITLE
As a Project Coordinator, I want to see the status of every form in the task list, so that I know what my progress is

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#368]
#### Description:

When looking at the task list, created in #366, the user should be able to tell whether each of the tasks is `Not Started`, `Complete`, `Incomplete` or has `Attention Required`

This needs to take into account pages that render multiple forms, e.g. contacts or managers

#### Acceptance Criteria:

Given that I am viewing a project revision task list
  - When none of a task's form(s) were updated since the previous revision
  Then the status in the task list should be `Not Started`

  - When some of a given task's form(s) was updated since the previous revision, their status is `staged`
  And the other forms were not updated (e.g. one contact was updated, the others were not)
  Then the status in the task list should be `Complete`

  - When some of a task's forms were updated since the previous revision
  And their status is `pending`
  Then the status in the task list should be `Incomplete`

  - When some of a task's forms were updated since the previous revision
  And their status is `staged`
  And they have validation errors
  Then the status in the task list should be `Attention Required`

#### Development Checklist:

- [ ] The task list should have a fixed width, to avoid page layout changes when the status of a task changes
- [ ] An `isPristine` computed column should be added to easily find out if a `form_change` was updated. Looking at `created_at` vs `updated_at` won't work since changes can be undone, this needs to compare the `new_form_data` against the previous form, using the column created in #374
- [ ] The `Attention Required` status should be bold
- [ ] Meets the DOD

#### Notes:

![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/4d600fe6-6dd5-4ad5-9659-1d09652b22be)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/368?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @pbastia

**Comment by gurjmatharu** [comment]
I may be mistaken but for the acceptance criteria point:
```
When some of a task's forms were updated since the previous revision
And their status is staged
And they have validation errors
Then the status in the task list should be Attention Required
```
The status should be pending, no?  I don't think we can stage forms with validation errors.

**Comment by gurjmatharu** [comment]
Also it looks like we're creating a project_contact form in status `pending` when we create a new project.  Is this expected behaviour?

**Comment by matthieu-foucault** [comment]
> The status should be pending, no? I don't think we can stage forms with validation errors.

No, this is correct. When you click on the submit button at the bottom of a form, it should change to `staged`, regardless of validation errors. Looking at the code in `ProjectForm` it does look like there's a bug:

```tsx
  const handleSubmit = async (e: ISubmitEvent<any>) => {
    await handleChange(e.formData, "staged");
    props.onSubmit();
  };
...
    <FormBase
        ...
        onSubmit={handleSubmit}
      >
        <Button type="submit" style={{ marginRight: "1rem" }}>
          Submit Project Overview
        </Button>
      </FormBase>

```

`onSubmit` will only be called if validation passes on the front-end, which means that, as you're indicating, a form failing validation can't be `staged`.

We probably want to separate `await handleChange(e.formData, "staged");` and `props.onSubmit();` into two different handlers.

```tsx
  const handleSubmit = async (e: ISubmitEvent<any>) => {
    props.onSubmit();
  };

  const handleSubmitClick = async () => {
    await handleChange(revision.projectFormChange.newFormData, "staged");
  };
...
    <FormBase
        ...
        onSubmit={handleSubmit}
      >
        <Button type="submit" style={{ marginRight: "1rem" }} onClick={handleSubmitClick}>
          Submit Project Overview
        </Button>
      </FormBase>

```

This fix may be required in the other forms too (not sure since they're actually multiple forms). As you fix this, make sure to add tests for this specific scenario: "clicking the submit button should stage a form with validation errors".

The idea of the `staged` status is to indicate that the user tried to submit the form (or navigated away from the page, to be added with #375). A `pending` form will likely fail validation, especially when you create a new project and all of the required fields are empty, and we don't want to bombard the user with validation errors and "Attention Required" statuses.

**Comment by matthieu-foucault** [comment]
> Also it looks like we're creating a project_contact form in status `pending` when we create a new project. Is this expected behaviour?

This is currently expected, yes, as a primary contact is required. The fact that the primary contact is in the "optional" section of the steps is an issue that we'll need to tackle at some point.

**Comment by gurjmatharu** [comment]
@matthieu-foucault thanks!  I'll add the form fix into this issue, and add tests.  One thing of note is that the project_contact form won't ever be in a state to show `Not started` as shown in the screenshot.

**Comment by LindsayMacfarlane** [comment]
Thanks @gurjmatharu ! Tested in dev by:
1) Adding a new project: status changed/updated accordingly as I completed the form. Status that I observed included incomplete, not started and completed. 
2) Editing an existing project: after editing an existing project, saving and then going back to that project - all the statuses appeared to revert to 'Not started'. 

Observations:
- when adding a new project, I wasn't able to save until all steps completed - even the optional steps. This may be captured in an existing bug ticket or it could be user error on my part. FYI @matthieu-foucault 
- I keep getting error messages, but have no idea what the error is (nothing is being displayed). I believe there is a bug ticket for this one as well.
