### ISSUE TITLE
User testing of milestone report prototype

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#404]
#### Describe the task

Take prototype out to ops team for testing, review and input. 

#### Acceptance Criteria

- [x] identify users from ops team to test wireframe
- [x] schedule testing session(s)
- [x] prepare script for test
- [x] get script approved by team
- [x] conduct session(s)

#### Additional context

- Note: depending on volume of feedback, updating wireframe could be pulled into its own ticket.

**Comment by elliottSlee** [comment]
dupe of #407, #408, #410

**Comment by LindsayMacfarlane** [comment]
@elliottSlee - Let's confirm with Suha before closing this ticket. We will created this ticket based on some next steps.

**Comment by LindsayMacfarlane** [comment]
re-opening to re-edit.

**Comment by LindsayMacfarlane** [comment]
@suha - please feel free to edit and update as you see fit. This ticket now captures the testing of the prototype related to milestone reports.

**Comment by suhafa** [comment]
We've one more session today, but I'd consider this ticket done.
