### ISSUE TITLE
User research related to milestone reports

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#409]
#### Describe the task

Complete user research related to milestone reports and how it can be included in the CIF app.

#### Acceptance Criteria
- [ ] Identify questions related to emissions intensity report
- [ ] Book meeting with Taylor and CIF team
- [ ] Identify fields/information that should be included
- [ ] Identify dependencies

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by LindsayMacfarlane** [comment]
Duplicate ticket. Closing.
