### ISSUE TITLE
User testing of milestone report wireframes

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#411]
#### Describe the task
Take wireframe out to ops team for testing, review and input.

#### Acceptance Criteria
- [x] identify users from ops team to test wireframe
- [x] schedule testing session(s)
- [x] conduct session(s)
- [ ] document feedback
- [ ] review feedback with dev team and prioritize feedback for development
- [ ] update wireframes based on feedback and priorities
- [ ] upload/attach wireframe to respective user stories (create user stories if required)

#### Additional context
- Note: depending on volume of feedback, updating wireframe could be pulled into its own ticket.

**Comment by suhafa** [comment]
same as #455 (compiling feedback) which we will tackle next sprint. Closing this.
