### ISSUE TITLE
Reiterate wireframe milestone report UI

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#412]
#### Describe the task

From feedback received during user review of initial milestone report UI (complete Sprint Mar 21 - April 1), incorporate feedback into the design.

#### Acceptance Criteria
- [x] ensure all fields are added from the milestone reports
- [x] compile feedback from usability session
- [x] meet with Elliot/ refer to Usability Feedback Miro board for any additional points
- [x] re-iterate wireframe design
- [x] review design with dev team for input
- [x] incorporate dev team feedback into wireframe

#### Additional context

-

**Comment by LindsayMacfarlane** [comment]
Hi @suhafa - feel free to edit and update this ticket. This one captures the iteration of the milestone report UI design.

**Comment by suhafa** [comment]
As far as feedback from dev team goes, this remains an ongoing process we can iron out in the next sprint as we condense feedback from our usability sessions. We've received some feedback here and there, which we can explore in depth. Closing this :D
