### ISSUE TITLE
Design milestone report prototype

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#436]
#### Design milestone report prototype that

- [x] shows the user adding 2 milestones. 
- [x] update status 
- [x] shows what screen looks like if there is a delay.
- [x] shows the user marking a report as received.
- [x] shows the user uploading the document.
- [x] shows the user adding a few comments about the milestone.
- [x] shows the user referencing the comment and updating it. 

#### Acceptance Criteria
- [x] Create additional wireframes to show interactive states
- [x] Workable screen flows that portray all the screen interactions mentioned above

#### Additional context
These tasks are supported by some of the feedback we got from our usability testing session with the Ops team in the previous sprint

- Ticket #412 deals with the user testing of the prototype

**Comment by suhafa** [comment]
Closing this, next step would be to get feedback from the team internally.

**Comment by LindsayMacfarlane** [comment]
Thanks @suhafa! I look forward to seeing them :)
