### ISSUE TITLE
As a Project coordinator, I want to see "Edit Project" in the task list, so that I know that I am editing a project

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#439]
#### Description:

The current text in the task list only makes sense when creating a project. This user story makes the wording in the task list change when the user is editing a project, as illustrated below

![image](https://user-images.githubusercontent.com/2684022/161160173-aa954e5f-cb2d-4203-8095-d6afe82ff099.png)

#### Acceptance Criteria:

Given that I am editing a project
When I view the task list
Then it has a text consistent with the "Editing" action

#### Development Checklist:

- [x] The `TaskList` component should have a `mode` variable, where `mode` is `"view" | "create" | "update"` (may have been added in #440 , depending which issue is done first). To avoid duplicating the mode determination logic, it should be done within the `TaskList`
- [x] To determine whether the page is in add or edit mode, one option would be to follow the `projectByProjectId` relation in the `TaskList_projectRevision` fragment. If the project doesn't exist yet, we are in "add" mode. We need to follow this relation to find the `proposalReference` either way (see below)
- [x] The title of the TaskList should be `Editing <proposal reference>`.
- [x] In `edit` mode, there will be no "optional" in the second section heading.
- [x] the links the the various forms should start with "Edit". 
- [x] The last step should say `Submit Changes` instead of `Submit Project` (ignore the screenshot above on this one)
- [ ] Meets the DOD

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/439?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @mikevespi @pbastia

**Comment by LindsayMacfarlane** [comment]
Awesome @gurjmatharu ! Thank you for your work on this one. I tested in dev by editing an existing project and editing a field within each task list. Worked as expected.
