### ISSUE TITLE
Compile feedback from wireframe usability session for Milestone reports

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#455]
- [x] document feedback
- [x] organize information
- [x] create sample user stories
- [x] review feedback + sample user stories with dev team
- [x] prioritize feedback for development
- [x] update wireframes based on feedback and priorities
- [ ] upload/attach wireframe to respective user stories (create user stories if required)

**Comment by suhafa** [comment]
Closing this issue, will be adding user stories/attaching wireframes to user stories today :D Thanks for everyone's help on this <3
