### ISSUE TITLE
As a project coordinator, I want to see next milestone due date in the project list so that I can easily determine what actions are necessary for projects.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#469]
#### Description:

During usability testing with the Ops team, they said they would like milestone due dates as a column in the projects list.

#### Acceptance Criteria:

Given I am a CIF administrator
When I am on the projects lists page
Then I can see a column with the date of the next reporting requirement due

Given I am a CIF administrator
When I am on the projects lists page
Then I can sort the projects by next requirement due date

#### Development Checklist:

- [x] An extra column showing the date of the next due reporting requirement
- [ ] The table header should use a `SortableHeader` in combination with a `SortOnlyFilter` 
- [ ] Meets the DOD

#### Notes:

-

**Comment by pbastia** [comment]
@elliottSlee @nanyangpro @suhafa Should we come up with a very simple design, to show the status of the reporting requirements in there too? (late, on track, ...)
I'm wondering if we can aggregate the date and the status in the same table cell / component, by making good use of symbology

**Comment by elliottSlee** [comment]
@pbastia That's exactly what Taylor suggested--green for good and orange or red marks or text to indicate other statuses in the project list. We may want to see what emerges after the TEIMP & budget are complete. I imagine there are going to be some important things there that will contribute. What do you think?

**Comment by suhafa** [comment]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/99216375/168179537-a1f928e5-aaf1-4a1d-a971-59c2023ed402.png">
Suggest the above wireframe design for showcasing milestone due dates at a glance, based on chat with @pbastia. We can use the filter function to sort between the different pill items (Upcoming, Late, Completed). Report statuses column can come after 'Status' column.

@elliottSlee Good point, there may be more columns depending on how we factor in Budgets and TEIMP. Perhaps a conversation for when we have the completed wireframes for TEIMP and Budget?

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/469?planning-poker) with ZenHub @BCerki @gurjmatharu @matthieu-foucault @mikevespi @pbastia @Sepehr-Sobhani

**Comment by pbastia** [comment]
This will reuse the computed column from #589

**Comment by LindsayMacfarlane** [comment]
@matthieu-foucault @pbastia - can this wait until after our first PROD launch? Trying to be mindful of what must be done to support our launch.

**Comment by pbastia** [comment]
I think this is a high impact / low effort feature to support their project operations, we should consider implementing it. It'll be able to answer the question "Which project requires my attention first?" by the ops team

**Comment by LindsayMacfarlane** [comment]
I believe this is in the dev environment already. Statuses are being displayed, but it doesn't look like a user can sort/filter, which is one of the acceptance criteria.

**Comment by pbastia** [comment]
Oops, the filtering is not there. I'll create a new card for it.
For dates, we can't really search, it doesn't make sense UX-wise. We would have to develop a control that allows queries of the type "before date x" or "between dates y and z"

**Comment by LindsayMacfarlane** [comment]
Thanks @pbastia ! The Ops team seemed very excited about this one during sprint demo today!
