### ISSUE TITLE
Card Sorting Research

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#519]
The CIF digital system contains many concepts and interfaces. It would be good to look into how the CIF team thinks about these. What's their mental schema of the following (incomplete) list:

- Reporting Operations
- Contacts
- Facilities
- Projects
- Milestone Reports
- Quarterly Reports
- Annual Reports
- Administrative Features

### Tasks
- [x] Find card sorting tool
- [x] Ask dev team for pages, features, concepts to be included in the task
- [x] Schedule sessions with Ops Team
- [x] Conduct sessions
- [x] Compile results from sessions

### Notes
- Results can be found on Miro Board and in Scrum Team [Channel](https://bcgov.sharepoint.com/:x:/t/00608-ScrumTeam/EWXONsMcVX1EgEUMKN5Q4vEBMcwHnAaK4G0LChZTs4SThg?e=tC4WY5).

**Comment by LindsayMacfarlane** [comment]
Hey @elliottSlee - I know you've mentioned this card sorting activity a few times recently and noticed it is still in the design backlog. Does this need to pulled into this sprint?

**Comment by elliottSlee** [comment]
@LindsayMacfarlane I planned it and did some research on whether card sorting or tree testing is better (and how to analyze these--for those interested [here's a paper](https://research-api.cbs.dk/ws/files/58892620/Ather_Nawaz_2012.pdf) on the comparison of different analysis techniques). The template is here: https://miro.com/app/board/uXjVO2cKeVs=/?share_link_id=246783055812. Maybe we can use the next sessions with the Ops team to double dip for this, too.

**Comment by LindsayMacfarlane** [comment]
@elliottSlee - I feel this ticket is complete?

**Comment by elliottSlee** [comment]
@LindsayMacfarlane Yes it is
