### ISSUE TITLE
Compile feedback and reiterate wireframes

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#544]
#### Describe the task

- Condense feedback received from # and present findings to the team

#### Tasks

- [ ] Compile findings
- [ ] Sort them into indexes
- [ ] Make iterations on the designs as per the findings
- [ ] Review them with the team via a Design/Dev sync

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - The refined designs (#642, #645, and #656) addressing gathered feedback have been presented to the devs, and further reviewed and finalized with @pbastia.
This ticket is ready for you to review/close.

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - During the office hour with Taylor, there were further things being brought up for Budgets, which upon double-check with the CIF Ops team early next week. Thus let's keep this card open for now.

(#642, #645, and #656 weren't be affected, but we may need one more user story for the Expenses and Payments Tracker section. After confirmation, I'll explain it to you before I add it.)

**Comment by suhafa** [comment]
Looks good @nanyangpro thanks for all your work on Budgets!

**Comment by LindsayMacfarlane** [comment]
Thank you so much @nanyangpro ! I really enjoyed observing and learning your process on how you define user stories, iterate designs and continuously validate with the Ops Team. It has helped make things very clear in terms of what needs to be built as part of this EPIC.
