### ISSUE TITLE
As an Ops Team Member, I want to enter the Performance Milestone Percentage for a project, so that I can track/update it (and use it to calculate the payment amount per milestone) for a successful proponent.

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#644]
#### Description:

Draft Figma design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=1488%3A2904

#### Acceptance Criteria:

Given I am a CIF project coordinator
When I am creating a new project
And I am on the project overview page
Then there is a field called 'Performance Milestone Percentage'

Given I am a CIF project coordinator
When I am editing an existing project
And I am on the project overview page
Then there is a field called 'Performance Milestone Percentage'

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
closing, captured in #642
