### ISSUE TITLE
As an Ops Team member, I want to see the (net and gross) payment amount (calculated) per milestone, so that I can inform CSNR to release the payment.

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#649]
#### Description:

Draft figma wireframe: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=1488%3A2662

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by dleard** [comment]
@LindsayMacfarlane @nanyangpro 
Do we have an example of how the net and gross payments are calculated somewhere?

**Comment by pbastia** [comment]
closing for #656

**Comment by nanyangpro** [comment]
Good question, @dleard.
The formula can be found in ["Expense Report Template - 2021.xlsx"](https://bcgov.sharepoint.com/:x:/t/00608-CIFInternalUsers/EUI8SqbfW2RAgbn0UWz66FgB6s-f_hbBj1TLWMMczIvoiA?e=1MwQ8V).
