### ISSUE TITLE
As a CIF administrator, I want to see when the next milestone report is due, so that I know if an action is required

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#685]
#### Description:

This is part 2 of #589, for milestones and annual reports.
It is now actionable as the rest of the forms have been refactored.

Wireframe: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=1301%3A2696

#### Acceptance Criteria:

Given I am a CIF ops team member
When I view a project
And I select one of the reporting requirements pages: annual reports, milestones
Then I can see a widget with the date when the next report is due

Given I am a CIF ops team member
When I am on a project's reporting requirements page: annual reports or milestones
Then I can see a widget with a link to the next report due

Given I am a CIF ops team member
When I am on a project's milestones form
Then I can see the report due indicator aggregating the data for all reporting requirements that are **not** quarterly or annual reports

#### Development Checklist:

- [ ] Update the `project_revision_upcoming_reporting_requirement_form_change` computed column to accept an array of values: this can be done by using the `string_to_array` function of postgres, and check for ` new_form_data->>'reportType'=any(...array...)`
- [ ] Document use of the `project_revision_upcoming_reporting_requirement_form_change` computed column
- [x] Re-use the `ReportDueIndicator` component on annual and milestone reports
- [x] Fix the spacing of the status badge per https://github.com/bcgov/cas-cif/issues/532#issuecomment-1158237140
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
repasting wireframe:
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/5ef19bf4-84bf-4af1-aee6-96e3fab490e2)

**Comment by matthieu-foucault** [comment]
Can we have a link to an up-to-date figma prototype, in case this gets updated and to ask questions to designers?

**Comment by BCerki** [comment]
I didn't do the first two AC because @dleard's work a couple of weeks ago already did what we needed it to

**Comment by LindsayMacfarlane** [comment]
Thanks! Looking at the final AC, I may need a bit of a walk through just so that I completely understand the functionality. I'm not 100% sure what is meant by aggregating all the data. For reference, I updated a project to have 3 milestones: 1) on track, 2) on track, 3) late. In the status, the status that was displayed was late. 

Observation:
When testing, I noticed that the project list page seemed to display the status of a quarterly report under the Milestone heading. I'll test again to see if I can reproduce and I'll confirm the functionality with the team.
