### ISSUE TITLE
As a project coordinator, I want to be able to undo changes on the milestone reports page

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#709]
#### Description:

Adding the undo changes button to the milestone reports form 

#### Acceptance Criteria:

Given that I am creating or editing a project, and that I have made changes to the milestone reports form
When clicking the "undo changes" button
Then all of my changes since the project was last submitted are reverted.

#### Development Checklist:

- [x] Adding `UndoChangesButton` component to the milestone reports form change
- [x] Meets the DOD

#### Notes:
- Related to #538, which implemented same feature on quarterly reports form

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! Tested in dev by:
1) Creating a new project. While creating a project, I added and undid changes related to a milestone report.
    - one observation: after undoing the milestone (and not creating a new one), the task list remained as 'filled'. 
    Wondering if that should have updated to 'Not Started'?

2)  Editing a milestone. Started by adding a milestone, then used 'undo changes' button to clear the information.
     - Similar to above, the task list indicated 'in progress'. Wondering if that should have gone back to 'Not Started'?

Other than those observations, which can be addressed in a separate ticket - this ticket meets the acceptance criteria. Closing issue.

FYI: @suhafa @nanyangpro
