### ISSUE TITLE
As a CIF user, I want to sort the projects by milestone due date, so that I can see which project needs attention next

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#726]
#### Description:

Missing piece from #469, we need to be able to sort by next requirement due date

![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/604f9521-f999-45f7-b079-d3cb4325c432)

note: the search filed is not applicable here

#### Acceptance Criteria:

Given I am a CIF administrator
When I am on the projects lists page
Then I can sort the projects by next requirement due date

#### Development Checklist:

- [x] The table header should use a `SortableHeader` in combination with a `SortOnlyFilter`
- [x] a computed column `project_next_milestone_due_date` returning the next milestone due date for a project
- [x] `project_next_milestone_due_date` is configured with `sortable: true` in `postgraphile.tags.json5`
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/726?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by pbastia** [comment]
@LindsayMacfarlane we just need a priority tag on this one

**Comment by LindsayMacfarlane** [comment]
Thanks @pbastia - I gave this one a high priority; however, if we are crunched for time to meet our release goals this can always wait until just after our first release.

**Comment by LindsayMacfarlane** [comment]
Note: if we complete this ticket, we can wrap up the Milestone EPIC :)

**Comment by LindsayMacfarlane** [comment]
Hi @sam-warren - just checking in on the status of this ticket. Do you need any support?

**Comment by sam-warren** [comment]
@LindsayMacfarlane It is ready for review :)

**Comment by LindsayMacfarlane** [comment]
Thank you @sam-warren - just double checking based on the acceptance criteria - should I also be seeing a filter?
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/9ae077b1-8152-49fa-a699-01bd202bd583)

**Comment by pbastia** [comment]
@LindsayMacfarlane filtering dates is much more complicated than a single field (date ranges? selecting inside or outside the range? ...) and provides little value in terms of usability, so our tables don't support it at this time. The original screenshot in the ticket is erroneous, and this card is only about the sorting

**Comment by LindsayMacfarlane** [comment]
Thanks for that clarification @pbastia!
