### ISSUE TITLE
As a CIF user, I want the statuses displayed in the task list to be clear, so that I can see the state of the project at a glance

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#729]
#### Description:

The TaskList component has received some design upgrades. Suha has provided a great description in figma of what should be shown when.
https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=1415%3A2663

#### Acceptance Criteria:

See figma
https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=1415%3A2663

#### Development Checklist:

- [ ] All items in figma wireframe are complete
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/729?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @mikevespi @Sepehr-Sobhani

**Comment by pbastia** [comment]
We would also need to support extra filters in `project_revision_overall_report_status(cif.project_revision, report_type, **filters)` to be able to differentiate quarterly, annual reports, milestones, ...

**Comment by LindsayMacfarlane** [comment]
Based on CIF prioritization session on Aug 16, 2022, this ticket needs further review. Low priority for the program area.

**Comment by LindsayMacfarlane** [comment]
Removing from CIF Project Lists Enhancements due to priority.
