### ISSUE TITLE
Database refactor - reporting_requirement, milestone, emission_intensity_report

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#761]
#### Describe the task

The database architecture has been updated, with a refactor needed for reporting requirements. We need to make changes to the following tables in the database as per our CIF Data Model miro board.

TEIMP Wireframe: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma

**reporting_requirement** (simplified, milestone/teimp fields removed):
  - id
  - report_type fkey -> report_type
  - project_id -> project
  - due_date
  - submitted_date
  - status
  - comment

**report_type** (update):
  - name
  - form_schema
  - is_milestone

**milestone** (created):
  - id
  - substantial_completion_date
  - certified_by
  - certifier_prof_designation
  - total_eligible_expenses

**emission_intensity_report** (created):
  - id
  - measurement_period_start_date
  - measurement_period_end_date
  - emission_functional_unit
  - production_functional_unit
  - baseline_emission_intensity
  - target_emission_intensity
  - post_project_emission_intensity
  - total_lifetime_emission_reduction
  - adjusted_emissions_intensity_performance

**emission_intensity_lookup** (created):
  - id
  - max_emission_intensity_performance
  - payment_percentage

**payment** (updated):
  - id
  - gross_amount
  - net_amount
  - date_sent_to_csnr

These architecture changes will cascade to the following computed columns (which will also cascade to the front-end graphql fragments and mutations):

**computed columns**:
`project_revision_upcoming_reporting_requirement_form_change`
`form_change_as_reporting_requirement`
`project_revision_milestone_report_statuses`

**mutations**:
`addReportingRequirementToRevision`
`updateReportingRequirementFormChange`
`discardReportingRequirementFormChange`

The mutations here will need to be re-defined in the database schema in order to make changes to all the related tables as necessary when updating/creating/discarding reporting_requirement recrods.

All items above will all be affected, this may not be an exhaustive list.

#### Acceptance Criteria

- [ ] The tables described above are added/updated in the database
- [ ] Computed columns are refactored
- [ ] New mutations are written in the database
- [ ] All cascading front-end changes to fragments and mutations are applied
