### ISSUE TITLE
As an Ops team member, when creating a milestone I only want the payment fields to show if the milestone type has associated expenses.

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-cif#853]
#### Description:

When creating or updating a milestone, only render the payment form if the milestone type has expenses associated with it. If a milestone does not have expenses in a given revision, it should not have a `form_change` record for `form_data_table_name` `payment`. 

A boolean `has_expenses` column should be added to the `report_type` table, and a computed column should be added to `reporting_requirement` that returns the value of `has_expenses` for the given `report_type`.

`has_expenses` values:
 Quarterly:  f
 Annual: f
 General Milestone: t
 Advanced Milestone: t
 Performance Milestone: t
 Reporting Milestone: f

#### Acceptance Criteria:

Given I am a CIF administrator
When I create or edit a milestone
And I select a milestone type with associated payments
Then I can see the payment form

Given I am a CIF administrator
When I create or edit a milestone
And I select a milestone type with **no** associated payments
Then there is no payment form on the page

#### Development Checklist:

- [ ] `has_expenses` column on `report_type`
- [ ] Computed column on `reporting_requirement` 
- [ ] Milestone form renders `payment` form based on value of `has_expenses` computed column
- [ ] `form_change` creation and deletion handled when milestone type is changed
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
Thanks @mikevespi! I tested in dev and observed the following:
- When I first add a milestone, the milestone type is pre-populated as general and I can see all the payment information. If I then select a milestone that doesn't require payment information (e.g., reporting) then the payment information disappears as expected. However, if I change the milestone back into one that requires payment information - the payment info doesn't come back. Bug? Expected behaviour? User error on my end?

**Comment by LindsayMacfarlane** [comment]
Based on standup August 4 standup conversation, this issue will be addressed in a ticket that Dylan has in PR review column. Can re-test after the other ticket has been merged. Moving this ticket to Accepted by PO.
