### ISSUE TITLE
As an Ops Team member, I want to see calculated payment amounts for this milestone, so that I can choose to override them

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#980]
#### Description:

Using the "calculated + adjusted" UI pattern on the net and gross payment amounts for a milestone

[Formula with examples](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EcXm1DnetBZNgFOkakDR_IEB1RS8r51PTHqH2h4C5L6URw?e=RbiNV2) - Please open it with the Word app instead of browser for formatting and better readability.

Discussion details in #656

Edit: Added `holdback_amount` to this card. It does not currently have fields in the schema for the calculated/adjusted holdback amount & will need to be added.

#### Acceptance Criteria:

Given I am an ops team member
When I enter milestone information
And I have entered the total eligible expenses for this milestone
Then I can see calculated values for holdback, net and gross payment amounts for this particular milestones

Given I am an ops team member
When I enter milestone information
Then I can choose to override the calculated holdback, net and gross payment information through "adjusted" fields

Edit:
Given I am an ops team member
When I am on the milestones page
Then I see a Maximum Amount This Milestone field (replaces the current `Maximum Amount` field, this is just a title change).

#### Development Checklist:

- [x] check in with @dleard to see what has been implemented as part of #986
- [x] milestone schema has `calculated_holdback_amount` and `adjusted_holdback_amount` fields for milestones with expenses.
- [x] milestone schema shows a title of `Maximum Amount This Milestone` for the `maximum_amount` field. Do not change the value of the json key, just the title attribute. Changing the key will be a larger refactor across the database that is probably unnecessary.
- [x] uses the "AdjustableCalculatedValueWidget" for `gross_payment_amount`, `holdback_amount` and `net_payment_amount` fields
- [x] Calculated values are retrieved from the form_change_**_this_miletstone computed columns created in #986
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
@dleard do you mind having a look at the developers checklist and remove what has been done in #986 ?

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/980?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Thank you @gurjmatharu Looks great. One observation: Should the Milestone Holdback Amount (Optional) (i.e., the override field) have a $ sign? 
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/5c741cd7-e696-4529-8b61-607c38764e61)

**Comment by LindsayMacfarlane** [comment]
Note: This feature will definitely require program area QA.

**Comment by pbastia** [comment]
It should definitely have one, tracked in https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1292

**Comment by gurjmatharu** [comment]
Forgot to comment here - this has been added.
<img width="573" alt="Screen Shot 2023-01-02 at 9 44 29 AM" src="https://user-images.githubusercontent.com/9407864/210246537-17601897-344f-459f-b907-2b06bcaf2d56.png">
