### ISSUE TITLE
As an Ops Team member, I want to see calculated expenses and payments to date when I enter milestone information, so that I have context for the other calculated values

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#984]
#### Description:

showing:
- total eligible expenses to date (calculated) + Tooltip
- total gross payment amount to date (calculated) + Tooltip
- total net payment amount to date (calculated) + Tooltip

https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=3713%3A2681
more details in #656

#### Acceptance Criteria:

Given I am an ops team member
When I enter milestone information
Then I can see calculated values for:
- total eligible expenses to date
- total gross payment amount to date
- total net payment amount to date

Given I am an ops team member
When I enter milestone information
And I look at the calculated fields above
Then I can see contextual help tooltips on each of these fields

#### Development Checklist:

- [x] check in with @dleard to see what of the following was done as part of #986
- [ ] create `reporting_requirement_net_payment_amount_to_date`
- [ ] create `reporting_requirement_gross_payment_amount_to_date` 
- [x] Create a `project_revision_total_eligible_expenses_to_date` computed column (done in #986)
- [ ] Add fields for these calculated values in the rjsf using a `ReadOnlyCalculatedValue` widget
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/984?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @pbastia @Sepehr-Sobhani

**Comment by pbastia** [comment]
As per discussion with the team, we chose to use the 'report received date' to calculate the 'payment to date'

**Comment by pbastia** [comment]
Here too, @dleard, do you mind having a look at the developers checklist and remove what has been done in #986 ?

**Comment by dleard** [comment]
@nanyangpro @LindsayMacfarlane Closing this card. It is no longer needed since the method for calculating Milestone expenses has changed. Individual Milestones no longer rely on data from the previous Milestone for these calculations.
